#!/bin/bash
#
# Copyright (C) 2020 azrim.
# Copyright (C) 2020 naonana.
# All rights reserved.

# Vars #
CHATID="chatidplaceholder"
TG_TOKEN="tgtokenplaceholder"
RELEASED=$(date +'%d %B %Y')
sep="|"

TG_DIR="${HOME}"/telegram
[[ ! -d "${TG_DIR}" ]] && git clone https://github.com/fabianonline/telegram.sh/ "${TELEGRAM_FOLDER}"
TELEGRAM="${TG_DIR}"/telegram

tg_msg() {
"${TELEGRAM}" -t "${TG_TOKEN}" -c "${CHATID}" -i "$BANNER" -M \
    "$(
                for POST in "${@}"; do
                        echo "${POST}"
                done
    )"
}

tg_sticker() {
curl -s -F chat_id="${CHATID}" -F sticker="$1" https://api.telegram.org/bot"${TG_TOKEN}"/sendSticker > /dev/null
}

post() {
[[ "${DEVICE}" = "surya" ]] && MAINTAINER="Hiitagiii" && PLING="https://www.pling.com/p/1452895/" && DEVICENAME="Poco X3 NFC"

[[ "${DEVICE}" = "whyred" ]] && MAINTAINER="eve_enryu" && PLING="https://www.pling.com/p/1408532/" && DEVICENAME="Redmi Note 5"

[[ "${DEVICE}" =~ "tulip" ]] && MAINTAINER="eve_enryu" && PLING="https://www.pling.com/p/1457781/" && DEVICENAME="Redmi Note 6 Pro"

[[ "${DEVICE}" = "miatoll" ]] && MAINTAINER="ThisIsTag" && PLING="https://www.pling.com/p/1437666/" && DEVICENAME="Xiaomi 720G series"

[[ "${DEVICE}" = "RMX1971" ]] && MAINTAINER="megakampang" && PLING="https://www.pling.com/p/1413659/" && DEVICENAME="Realme 5 Pro"

[[ "${DEVICE}" = "RMX1851" ]] && MAINTAINER="Artoriaa" && PLING="https://www.pling.com/p/1439222/" && DEVICENAME="Realme 3 Pro"

[[ "${DEVICE}" = "onclite" ]] && MAINTAINER="BryanHafidzTorvalds" && PLING="https://www.pling.com/p/1464631/" && DEVICENAME="Redmi 7"

[[ "${DEVICE}" = "tissot" ]] && MAINTAINER="Yincen" && PLING="https://www.pling.com/p/1408418/" && DEVICENAME="MI A1"

[[ "${DEVICE}" = "ginkgo" ]] && MAINTAINER="fakhiralkda" && PLING="https://www.pling.com/p/1413487/" && DEVICENAME="Redmi Note 8"

[[ -z "${GROUP}" ]] && GROUP="silont_support"

[[ -z "${XDA}" ]] && xdathread="${XDA}" || xdathread="🔹 [XDA Thread](${XDA})"

[[ -z "${CODENAME}" ]] && KERNEL_CODENAME="${CODENAME}" || KERNEL_CODENAME="ℹ️ Codename: *$CODENAME*"

BANNER_LINK="https://github.com/silont-project/official-devices/raw/master/${DEVICE}/${DEVICE}.png"
BANNER="$HOME/$DEVICE.png"

[[ ! -f "${BANNER}" ]] && wget "${BANNER_LINK}" -O "${BANNER}"

l1="${KERNEL_CODENAME}"
l2="[Download]($PLING)"
l3="[Cl & Notes](https://github.com/silont-project/official-devices/raw/master/${DEVICE}/${FILENAME}.txt)"
l4="[Support group](https://t.me/$GROUP)"
l41="[Group](https://t.me/silont_support)"
l42="[Channel](https://t.me/silont_updates)"
l5="$l41 $sep $l42"
l6="$xdathread"

tg_sticker "CAACAgUAAxkBAAE-BLRf6Zi5wdrMZaYVBS0RWaj0CqJd2gACYQIAAndoICyTqqxZHIg5px4E"
tg_msg \
"📲 *SiLonT Kernel* $sep $DEVICE ($DEVICENAME)" \
"🔨 by @$MAINTAINER" \
"" \
"🗓 Released: *$RELEASED*" \
"$l1" \
"" \
"🔹 $l2" \
"🔹 $l3" \
"🔹 $l4" \
"$l6" \
"" \
"*Join* $l5" \
"#${DEVICENAME// /} #$DEVICE #StayNgelonT"
}

help() {
echo -e "Simple script to post silont kernel updates.\n" \
"\n" \
"Usage: post [-option] arguments\n" \
"options:\n" \
"* d - device codename (e.g. surya)\n" \
"* f - changelog filename without .txt (e.g. SiLonT-Surya-tooru-20201212-1621)\n" \
"* c - kernel codename (e.g. tooru)\n" \
"  g - group username (e.g. azrim_lab - don't declare if don't have any)\n" \
"  x - xda thread link (e.g. https://xda-developers.com/blablabla - don't declare if don't have any)\n" \
"  h - Print this Help."

"* is necessary, must be set"
}

while getopts d:f:c:g:x:h flag
do
    case "${flag}" in
        d) DEVICE=${OPTARG};;
        f) FILENAME=${OPTARG};;
        c) CODENAME=${OPTARG};;
        g) GROUP=${OPTARG};;
        x) XDA=${OPTARG};;
        h) help
           exit;;
        \?) # Incorrect option
           echo "Error: Invalid option !"
           echo "Use post -h for available options"
           exit;;
    esac
done

[[ -z $1 ]] && echo "ERROR: No option" && echo "Use post -h for available options" && exit

[[ -z $DEVICE ]] && echo "ERROR: Device not set" && exit

[[ -z $FILENAME ]] && echo "ERROR: File name not set" && exit

post
