#!/bin/bash
#
# Copyright (C) 2020 azrim.
# Copyright (C) 2021 nao04.
# All rights reserved.

# Vars #
CHATID="chatidplaceholder"
TG_TOKEN="tgtokenplaceholder"
DATE=$(date +'%d %B %Y')

TG_DIR=$(pwd)/telegram
[[ ! -d "$TG_DIR" ]] && git clone https://github.com/fabianonline/telegram.sh/ "$TG_DIR"
TELEGRAM="$TG_DIR"/telegram

tg_msg() {
"$TELEGRAM" -t "$TG_TOKEN" -c "$CHATID" -i "$BANNER" -M \
    "$(
                for POST in "${@}"; do
                        echo "${POST}"
                done
    )"
}

tg_sticker() {
curl -s -F chat_id="$CHATID" -F sticker="$1" https://api.telegram.org/bot"$TG_TOKEN"/sendSticker > /dev/null
}

post() {
[[ "$DEVICE" = "surya" ]] && MAINTAINER="Hiitagiii" && PLING="https://www.pling.com/p/1452895/" && DEVICENAME="Poco X3 NFC"

[[ "$DEVICE" = "whyred" ]] && MAINTAINER="eve\_enryu" && PLING="https://www.pling.com/p/1491356/" && DEVICENAME="Redmi Note 5 Pro"

[[ "$DEVICE" = "tulip" ]] && MAINTAINER="eve\_enryu" && PLING="https://www.pling.com/p/1491356/" && DEVICENAME="Redmi Note 6 Pro"

[[ "$DEVICE" = "lavender" ]] && MAINTAINER="eve\_enryu" && PLING="https://www.pling.com/p/1491359/" && DEVICENAME="Redmi Note 7"

[[ "$DEVICE" = "jane" ]] && MAINTAINER="eve\_enryu" && PLING="https://www.pling.com/p/1491359/" && DEVICENAME="Mi A26X"

[[ "$DEVICE" = "miatoll" ]] && MAINTAINER="ThisIsTag" && PLING="https://www.pling.com/p/1437666/" && DEVICENAME="Xiaomi 720G series"

[[ "$DEVICE" = "RMX1971" ]] && MAINTAINER="naogairu" && PLING="https://www.pling.com/p/1413659/" && DEVICENAME="Realme 5 Pro"

[[ "$DEVICE" = "onclite" ]] && MAINTAINER="BryanHafidzTorvalds" && PLING="https://www.pling.com/p/1464631/" && DEVICENAME="Redmi 7"

[[ "$DEVICE" = "tissot" ]] && MAINTAINER="Yincen" && PLING="https://www.pling.com/p/1408418/" && DEVICENAME="MI A1"

[[ "$DEVICE" = "ginkgo" ]] && MAINTAINER="fakhiralkda" && PLING="https://www.pling.com/p/1413487/" && DEVICENAME="Redmi Note 8"

[[ "$DEVICE" = "RMX1911" ]] && MAINTAINER="dodyirawan85" && PLING="https://www.pling.com/p/1519770/" && DEVICENAME="Realme Trinket"

[[ "$DEVICE" = "vayu" ]] && MAINTAINER="Artoriaa" && PLING="https://www.pling.com/p/1544835/" && DEVICENAME="Poco X3 Pro"

BANNER_LINK="https://github.com/silont-project/official-devices/raw/master/$DEVICE/$DEVICE.png"
BANNER="$DEVICE.png"

[[ ! -f "$BANNER" ]] && wget "$BANNER_LINK" -O "$BANNER"
[[ ! -z "$XDA" ]] && XDA_THREAD="🔹 [XDA](${XDA})
" # This newline is intentional
[[ ! -z "$DEVICE_GROUP" ]] && DEVICE_GROUP="[Support group](https://t.me/$GROUP)" || DEVICE_GROUP="[Support group](https://t.me/silont_support)"

LINK="[Download]($PLING)"
CHANGELOG="[Changelogs & Notes](https://github.com/silont-project/official-devices/raw/master/$DEVICE/$FILENAME.txt)"
GROUP="[Group](https://t.me/silont_support)"
CHANNEL="[Channel](https://t.me/silont_updates)"

tg_sticker "CAACAgUAAxkBAAE-BLRf6Zi5wdrMZaYVBS0RWaj0CqJd2gACYQIAAndoICyTqqxZHIg5px4E"
tg_msg \
"📲 *SiLonT Kernel* | $DEVICE ($DEVICENAME)" \
"🔨 by @$MAINTAINER" \
"" \
"🗓 Released: *$DATE*" \
"ℹ️ Codename: *$CODENAME*" \
"" \
"🔹 $LINK" \
"🔹 $CHANGELOG" \
"🔹 $DEVICE_GROUP" \
"$XDA_THREAD" \
"*Join* $GROUP | $CHANNEL" \
"#${DEVICENAME// /} #$DEVICE #StayNgelonT"
}

help() {
echo -e "Script to automate SiLonT kernel releases.\n" \
"\n" \
"Usage: ./post [-option] arguments\n" \
"options:\n" \
"* d - Device codename (e.g. surya)\n" \
"* f - Changelog file name without .txt (e.g. SiLonT-Surya-tooru-20201212-1621)\n" \
"  c - Kernel codename (e.g. tooru)\n" \
"  g - Group username (e.g. azrim_lab - Don't set if don't have any)\n" \
"  x - XDA thread link (e.g. https://xda-developers.com/blablabla - Don't set if don't have any)\n" \
"  h - Print this help." \
"\n" \
"\n" \
"Arguments with * means necessary, must be set"
}

while getopts d:f:c:g:x:h flag
do
    case "$flag" in
        d) DEVICE=${OPTARG};;
        f) FILENAME=${OPTARG};;
        c) CODENAME=${OPTARG};;
        g) DEVICE_GROUP=${OPTARG};;
        x) XDA=${OPTARG};;
        h) help
           exit;;
        \?) # Incorrect option
           echo "Error: Invalid option !"
           echo "Use post -h to list available arguments"
           exit;;
    esac
done

[[ -z $1 ]] && echo "ERROR: No argument given" && echo "Use post -h for available options" && exit

[[ -z $DEVICE ]] && echo "ERROR: Device not set" && exit

[[ -z $FILENAME ]] && echo "ERROR: File name not set" && exit

post
